CREATE TABLE  "CT_IMEDIMAGE" 
   (	"CONTENTID" NUMBER(10,0) NOT NULL ENABLE, 
	"REVISIONID" NUMBER(10,0) NOT NULL ENABLE, 
	"ALT" VARCHAR2(200), 
	"IMG" BLOB, 
	"IMG_TYPE" VARCHAR2(100), 
	"IMG_FILENAME" VARCHAR2(200), 
	"IMG_EXT" VARCHAR2(50), 
	"IMG_SIZE" VARCHAR2(50), 
	"IMG_HEIGHT" VARCHAR2(50), 
	"IMG_WIDTH" VARCHAR2(50), 
	 CONSTRAINT "PK_CT_IMEDIMAGE" PRIMARY KEY ("CONTENTID", "REVISIONID") ENABLE
   )
/
CREATE TABLE  "CT_IMEDIMAGE_SIZED" 
   (	"CONTENTID" NUMBER(10,0) NOT NULL ENABLE, 
	"REVISIONID" NUMBER(10,0) NOT NULL ENABLE, 
	"SYSID" NUMBER(10,0) NOT NULL ENABLE, 
	"SORTRANK" NUMBER(10,0), 
	"SIZE_CODE" VARCHAR2(50), 
	"SIZED_IMG" BLOB, 
	"SIZED_IMG_TYPE" VARCHAR2(200), 
	"SIZED_IMG_FILENAME" VARCHAR2(200), 
	"SIZED_IMG_EXT" VARCHAR2(50), 
	"SIZED_IMG_HEIGHT" VARCHAR2(50), 
	"SIZED_IMG_WIDTH" VARCHAR2(50), 
	"SIZED_IMG_SIZE" VARCHAR2(50), 
	 CONSTRAINT "PK_CT_IMEDIMAGE_SIZED" PRIMARY KEY ("CONTENTID", "REVISIONID", "SYSID") ENABLE
   )
/
